### ISSUE TITLE
It doesn't work on iOS

### ISSUE THREAD

**Issue by vickyming** [xgfe/react-native-datepicker#18]
After update to 
"react": "^15.2.0",
"react-native": "^0.28.0"
it shows empty datepicker on iOS.

**Comment by enapupe** [comment]
I have the same issue on the simulator. But it is working fine on the actual device.. 😕

**Comment by feyy** [comment]
#[13](https://github.com/xgfe/react-native-datepicker/issues/13). Because DatePickerIOS didn't have specific width([Removed hard-coded DatePicker width
](https://github.com/facebook/react-native/commit/002024cc456246761421f6e5c354466baa819843#diff-0cd1ca16f12d89133cb43f7f8aca9073L145)).
You can use customStyles to overwrite the align styles:

```
customStyles={{
  datePicker: {
    alignItems: 'stretch'
  }
}}
```

And will resolve it in v1.3 this week.
