### ISSUE TITLE
One day before

### ISSUE THREAD

**Issue by risuiar** [xgfe/react-native-datepicker#94]
Thank you for your work!

My Problem: If I have a date for example 1980-10-24 and I open it, I see 23 Oktober 1970, alwas y day before, is this a bug or I am doing something wrong?

**Comment by risuiar** [comment]
Very strange, now works, maybe some xcode bug. Thank you.

**Comment by nimish-gupta** [comment]
@risuiar same bug , any solution

**Comment by risuiar** [comment]
Check input Date

**Comment by bed42** [comment]
I faced this issue and determined that it was due to an undefined timeZoneOffset being passed to iOS causing massive unpredictability. Fix here https://github.com/xgfe/react-native-datepicker/pull/194

**Comment by victoriomolina** [comment]
@bed42 @risuiar after this code update, the problem still persists. I am getting the day before when I choose one day (I am using last version of the package).

Testing on a standalone App in my iOS emulator.

Any ideas? Also, this is really random, because when I use `display=“inline”` the date is correct… the problem comes with `display=“spinner”`.

Similar bug [here](https://stackoverflow.com/questions/71025060/react-native-datetimepicker-datetimepicker-is-1-day-off).
